import { ArchitectureModel } from "@/lib/schemas/architecture";

export const aiCodeReviewerModel: ArchitectureModel = {
  system: "ai-code-reviewer",
  disclosure: "full",
  layers: [
    {
      id: "context",
      title: "System Context",
      groups: [],
      nodes: [
        {
          id: "developer",
          label: "Developer",
          kind: "external",
          tech: [],
          summary: "Engineer opening a Pull Request.",
          pos: { x: 10, y: 50 },
        },
        {
          id: "github",
          label: "GitHub Webhooks",
          kind: "external",
          tech: ["GitHub App"],
          summary: "Source of truth for PR events and code.",
          pos: { x: 30, y: 50 },
        },
        {
          id: "acr-system",
          label: "AI Code Reviewer",
          kind: "service",
          tech: ["TypeScript", "Node.js"],
          summary: "The core review engine evaluating the diff.",
          rationale: "Centralizes all review logic independently from the VCS.",
          tradeoffs: ["Needs strict rate limiting", "High memory usage for large diffs"],
          decisionRefs: ["decision-2"],
          pos: { x: 60, y: 50 },
        },
        {
          id: "llm-provider",
          label: "LLM Providers",
          kind: "external",
          tech: ["Anthropic", "OpenAI", "Google", "Groq", "Ollama"],
          summary: "Model-agnostic reasoning engine behind one interface — the runtime is not locked to any single provider.",
          pos: { x: 90, y: 50 },
        },
      ],
      edges: [
        { id: "ce1", from: "developer", to: "github", kind: "async", label: "Open PR" },
        { id: "ce2", from: "github", to: "acr-system", kind: "async", label: "Webhook (pr.opened)" },
        { id: "ce3", from: "acr-system", to: "llm-provider", kind: "sync", label: "Prompt / Tool Use" },
        { id: "ce4", from: "acr-system", to: "github", kind: "async", label: "Note review comments" },
      ],
    },
    {
      id: "container",
      title: "Inside the Reviewer",
      groups: [
        { id: "g1", label: "Ingestion Pipeline", nodeIds: ["webhook-handler", "diff-parser"], pos: { x: 5, y: 5 }, dims: { w: 30, h: 40 } },
        { id: "g2", label: "Agent Runtime", nodeIds: ["agent-loop", "ast-analyzer", "vector-retriever"], pos: { x: 40, y: 5 }, dims: { w: 30, h: 60 } },
        { id: "g3", label: "Data Layer", nodeIds: ["pg-db", "redis-cache"], pos: { x: 75, y: 5 }, dims: { w: 20, h: 40 } },
      ],
      nodes: [
        {
          id: "webhook-handler",
          label: "Webhook Handler",
          kind: "service",
          tech: ["Next.js Route"],
          summary: "Receives and validates GitHub events.",
          rationale: "Serverless function for instant scaling under webhook spikes.",
          tradeoffs: ["Cold starts delay initial processing"],
          pos: { x: 20, y: 15 },
        },
        {
          id: "diff-parser",
          label: "Diff Parser",
          kind: "pipeline-step",
          tech: ["parse-diff"],
          summary: "Splits raw git diffs into analyzable chunks.",
          rationale: "Normalizes various diff formats into a strict schema.",
          tradeoffs: ["Struggles with massive refactors (>20k lines)"],
          pos: { x: 20, y: 35 },
        },
        {
          id: "agent-loop",
          label: "Agent Runtime",
          kind: "agent",
          tech: ["TypeScript (Custom)"],
          summary: "Hand-written ReAct loop driving the review process.",
          rationale: "Off-the-shelf frameworks lacked type safety for tool inputs.",
          tradeoffs: ["More maintenance surface", "Harder to debug state transitions"],
          decisionRefs: ["decision-1"],
          pos: { x: 55, y: 25 },
        },
        {
          id: "ast-analyzer",
          label: "AST Chunker",
          kind: "service",
          tech: ["tree-sitter"],
          summary: "Tree-sitter AST parsing produces code-aware chunks at function and class boundaries for indexing and retrieval.",
          rationale: "Structure-aware chunking beats line-based splitting for retrieval quality.",
          tradeoffs: ["Currently parses Python and TypeScript/JavaScript"],
          pos: { x: 55, y: 45 },
        },
        {
          id: "vector-retriever",
          label: "Hybrid Retriever",
          kind: "service",
          tech: ["BM25", "Voyage", "pgvector", "Cohere"],
          summary: "Agent tool: hybrid code retrieval (BM25 + Voyage embeddings over pgvector), fused with Reciprocal Rank Fusion and reranked by a Cohere cross-encoder.",
          rationale: "Retrieves the ~3-5% of the repo that is load-bearing for a given diff — exact symbols and semantic intent.",
          tradeoffs: ["Requires re-indexing when the repo changes"],
          decisionRefs: ["decision-2"],
          pos: { x: 55, y: 65 },
        },
        {
          id: "pg-db",
          label: "PostgreSQL",
          kind: "store",
          tech: ["Supabase", "pgvector"],
          summary: "Stores PR/review state, code-chunk embeddings, and the semantic retrieval cache.",
          rationale: "Relational state and vector storage in one datastore.",
          tradeoffs: ["Vertical scaling limits"],
          pos: { x: 85, y: 15 },
        },
        {
          id: "redis-cache",
          label: "Cache Layer",
          kind: "store",
          tech: ["Redis"],
          summary: "Exact-match response cache (Redis) plus pgvector semantic cache, so repeated retrievals and identical reviews aren't re-paid for.",
          rationale: "Cost and latency discipline — caching is first-class, not bolted on.",
          tradeoffs: ["Another stateful dependency"],
          pos: { x: 85, y: 35 },
        },
        {
          id: "eval-pipeline",
          label: "Eval Harness",
          kind: "pipeline-step",
          tech: ["LLM-as-judge", "CI"],
          summary: "Versioned golden dataset scored by a versioned LLM-as-judge plus deterministic checks; the below-bar baseline is committed to the repo.",
          rationale: "Treats prompt engineering as software engineering — regressions block the merge.",
          tradeoffs: ["Dataset maintenance is expensive"],
          decisionRefs: ["decision-3"],
          pos: { x: 50, y: 85 },
        },
      ],
      edges: [
        { id: "e1", from: "webhook-handler", to: "diff-parser", kind: "sync" },
        { id: "e2", from: "diff-parser", to: "agent-loop", kind: "sync", label: "Parsed diff" },
        { id: "e3", from: "agent-loop", to: "redis-cache", kind: "sync", label: "Check cache" },
        { id: "e4", from: "agent-loop", to: "ast-analyzer", kind: "sync", label: "Call Tool" },
        { id: "e5", from: "agent-loop", to: "vector-retriever", kind: "sync", label: "Call Tool" },
        { id: "e6", from: "vector-retriever", to: "pg-db", kind: "sync", label: "Select vectors" },
        { id: "e7", from: "agent-loop", to: "pg-db", kind: "async", label: "Store results" },
        { id: "e8", from: "pg-db", to: "eval-pipeline", kind: "data", label: "CI on every change" },
      ],
    },
  ],
  flows: [
    {
      id: "pr-review",
      title: "PR review end-to-end",
      layerId: "container",
      summary: "How a PR goes from webhook to generated comments.",
      steps: [
        { nodeId: "webhook-handler", caption: "Webhook validates the GitHub signature (delivery path in progress)." },
        { nodeId: "diff-parser", caption: "Payload is mapped to a standard diff format." },
        { nodeId: "agent-loop", caption: "The agent analyzes the diff and decides which tools to call." },
        { nodeId: "redis-cache", caption: "Agent checks the response and semantic caches before spending tokens." },
        { nodeId: "vector-retriever", caption: "Agent retrieves the load-bearing repo context for the diff (hybrid search + rerank)." },
        { edgeId: "e7", caption: "The final synthesized review is saved to the DB before posting to GitHub." },
      ],
    },
    {
      id: "evals",
      title: "Index & eval pipeline",
      layerId: "container",
      summary: "How the system maintains quality over time.",
      steps: [
        { nodeId: "pg-db", caption: "Run telemetry and review history are persisted for tracing." },
        { nodeId: "eval-pipeline", caption: "On every change, CI runs the agent against the committed golden dataset; a score below the baseline blocks the merge." },
      ],
    },
  ],
};
