import { ArchitectureModel } from "@/lib/schemas/architecture";

export const aiCodeReviewerModel: ArchitectureModel = {
  system: "ai-code-reviewer",
  disclosure: "full",
  layers: [
    {
      id: "context",
      title: "System Context",
      groups: [],
      nodes: [
        {
          id: "developer",
          label: "Developer",
          kind: "external",
          tech: [],
          summary: "Engineer opening a Pull Request.",
          pos: { x: 10, y: 50 },
        },
        {
          id: "github",
          label: "GitHub Webhooks",
          kind: "external",
          tech: ["GitHub App"],
          summary: "Source of truth for PR events and code.",
          pos: { x: 30, y: 50 },
        },
        {
          id: "acr-system",
          label: "AI Code Reviewer",
          kind: "service",
          tech: ["TypeScript", "Node.js"],
          summary: "The core review engine evaluating the diff.",
          rationale: "Centralizes all review logic independently from the VCS.",
          tradeoffs: ["Needs strict rate limiting", "High memory usage for large diffs"],
          decisionRefs: ["hybrid-retrieval"],
          pos: { x: 60, y: 50 },
        },
        {
          id: "llm-provider",
          label: "Claude 3.5 API",
          kind: "external",
          tech: ["Anthropic"],
          summary: "The reasoning engine generating review comments.",
          pos: { x: 90, y: 50 },
        },
      ],
      edges: [
        { id: "ce1", from: "developer", to: "github", kind: "async", label: "Open PR" },
        { id: "ce2", from: "github", to: "acr-system", kind: "async", label: "Webhook (pr.opened)" },
        { id: "ce3", from: "acr-system", to: "llm-provider", kind: "sync", label: "Prompt / Tool Use" },
        { id: "ce4", from: "acr-system", to: "github", kind: "async", label: "Post review comments" },
      ],
    },
    {
      id: "container",
      title: "Inside the Reviewer",
      groups: [
        { id: "g1", label: "Ingestion Pipeline", nodeIds: ["webhook-handler", "diff-parser"], pos: { x: 5, y: 5 }, dims: { w: 30, h: 40 } },
        { id: "g2", label: "Agent Runtime", nodeIds: ["agent-loop", "ast-analyzer", "vector-retriever"], pos: { x: 40, y: 5 }, dims: { w: 30, h: 60 } },
        { id: "g3", label: "Data Layer", nodeIds: ["pg-db", "redis-cache"], pos: { x: 75, y: 5 }, dims: { w: 20, h: 40 } },
      ],
      nodes: [
        {
          id: "webhook-handler",
          label: "Webhook Handler",
          kind: "service",
          tech: ["Next.js Route"],
          summary: "Receives and validates GitHub events.",
          rationale: "Serverless function for instant scaling under webhook spikes.",
          tradeoffs: ["Cold starts delay initial processing"],
          pos: { x: 20, y: 15 },
        },
        {
          id: "diff-parser",
          label: "Diff Parser",
          kind: "pipeline-step",
          tech: ["parse-diff"],
          summary: "Splits raw git diffs into analyzable chunks.",
          rationale: "Normalizes various diff formats into a strict schema.",
          tradeoffs: ["Struggles with massive refactors (>20k lines)"],
          pos: { x: 20, y: 35 },
        },
        {
          id: "agent-loop",
          label: "Agent Runtime",
          kind: "agent",
          tech: ["TypeScript (Custom)"],
          summary: "Hand-written ReAct loop driving the review process.",
          rationale: "Off-the-shelf frameworks lacked type safety for tool inputs.",
          tradeoffs: ["More maintenance surface", "Harder to debug state transitions"],
          decisionRefs: ["custom-agent-runtime"],
          pos: { x: 55, y: 25 },
        },
        {
          id: "ast-analyzer",
          label: "AST Tool",
          kind: "service",
          tech: ["Babel/Parser"],
          summary: "Agent tool to check syntax and type constraints.",
          rationale: "Prevents LLM hallucination of code structures.",
          tradeoffs: ["Only supports TS/JS currently"],
          pos: { x: 55, y: 45 },
        },
        {
          id: "vector-retriever",
          label: "Vector Retriever",
          kind: "service",
          tech: ["pgvector"],
          summary: "Agent tool to find similar past PRs.",
          rationale: "Helps enforce team conventions by referencing past reviews.",
          tradeoffs: ["Requires constant syncing of main branch"],
          decisionRefs: ["hybrid-retrieval"],
          pos: { x: 55, y: 65 },
        },
        {
          id: "pg-db",
          label: "PostgreSQL",
          kind: "store",
          tech: ["RDS"],
          summary: "Stores PR state, embeddings, and telemetry.",
          rationale: "Consolidated state and vector storage.",
          tradeoffs: ["Vertical scaling limits"],
          pos: { x: 85, y: 15 },
        },
        {
          id: "redis-cache",
          label: "Redis Queue",
          kind: "queue",
          tech: ["BullMQ"],
          summary: "Deduplicates and rate-limits review jobs.",
          rationale: "Prevents overwhelming the Anthropic API.",
          tradeoffs: ["Another stateful dependency"],
          pos: { x: 85, y: 35 },
        },
        {
          id: "eval-pipeline",
          label: "Eval Pipeline",
          kind: "pipeline-step",
          tech: ["Vitest"],
          summary: "Nightly regressions checks against a golden dataset.",
          rationale: "Ensures prompt updates don't degrade review quality.",
          tradeoffs: ["Dataset maintenance is expensive"],
          decisionRefs: ["versioned-evals"],
          pos: { x: 50, y: 85 },
        },
      ],
      edges: [
        { id: "e1", from: "webhook-handler", to: "diff-parser", kind: "sync" },
        { id: "e2", from: "diff-parser", to: "redis-cache", kind: "async", label: "Queue Job" },
        { id: "e3", from: "redis-cache", to: "agent-loop", kind: "async", label: "Worker picks job" },
        { id: "e4", from: "agent-loop", to: "ast-analyzer", kind: "sync", label: "Call Tool" },
        { id: "e5", from: "agent-loop", to: "vector-retriever", kind: "sync", label: "Call Tool" },
        { id: "e6", from: "vector-retriever", to: "pg-db", kind: "sync", label: "Select vectors" },
        { id: "e7", from: "agent-loop", to: "pg-db", kind: "async", label: "Store results" },
        { id: "e8", from: "pg-db", to: "eval-pipeline", kind: "data", label: "Nightly run" },
      ],
    },
  ],
  flows: [
    {
      id: "pr-review",
      title: "PR review end-to-end",
      layerId: "container",
      summary: "How a PR goes from webhook to generated comments.",
      steps: [
        { nodeId: "webhook-handler", caption: "Webhook validates GitHub signature." },
        { nodeId: "diff-parser", caption: "Payload is mapped to a standard diff format." },
        { nodeId: "redis-cache", caption: "Job is queued to respect Anthropic rate limits." },
        { nodeId: "agent-loop", caption: "The agent analyzes the diff and decides which tools to call." },
        { nodeId: "vector-retriever", caption: "Agent retrieves similar past PRs to check for repeating mistakes." },
        { edgeId: "e7", caption: "The final synthesized comments are saved to the DB before posting to GitHub." },
      ],
    },
    {
      id: "evals",
      title: "Index & eval pipeline",
      layerId: "container",
      summary: "How the system maintains quality over time.",
      steps: [
        { nodeId: "pg-db", caption: "Historical PRs and manual corrections are logged." },
        { nodeId: "eval-pipeline", caption: "A nightly script runs the current prompt against the historical dataset." },
      ],
    },
  ],
};
