import { ArchitectureModel } from "@/lib/schemas/architecture";

export const multiAgentOpsModel: ArchitectureModel = {
  system: "multi-agent-ops",
  disclosure: "conceptual",
  layers: [
    {
      id: "container",
      title: "Conceptual Pattern View",
      groups: [],
      nodes: [
        {
          id: "ui-client",
          label: "Agent Copilot UI",
          kind: "client",
          tech: ["React Native Web", "XState"],
          summary: "Unified frontend interface for customer support representatives.",
          illustrative: true,
          pos: { x: 50, y: 10 },
        },
        {
          id: "api-gateway",
          label: "API Gateway",
          kind: "service",
          tech: ["NestJS", "GraphQL"],
          summary: "Entry point for all client requests, handling auth and routing.",
          rationale: "Decouples client-facing API from internal agent orchestration.",
          tradeoffs: ["Adds a network hop", "Requires schema syncing"],
          illustrative: true,
          pos: { x: 50, y: 30 },
        },
        {
          id: "orchestrator",
          label: "Agent Orchestrator",
          kind: "agent",
          tech: ["Node.js", "State Machine"],
          summary: "State machine routing tasks to specialized sub-agents.",
          rationale: "Centralizes prompt chaining and tool access control.",
          tradeoffs: ["Single point of failure for reasoning", "High latency overhead"],
          illustrative: true,
          pos: { x: 50, y: 50 },
        },
        {
          id: "retrieval-agent",
          label: "Retrieval Sub-Agent",
          kind: "agent",
          tech: ["Python", "Voyage AI"],
          summary: "Specialized in fetching relevant knowledge base articles.",
          rationale: "Isolates embedding and vector search logic from reasoning.",
          tradeoffs: ["Increases overall system complexity"],
          illustrative: true,
          pos: { x: 25, y: 70 },
        },
        {
          id: "action-agent",
          label: "Action Sub-Agent",
          kind: "agent",
          tech: ["Python", "Tool Calling"],
          summary: "Executes mutations against internal CRMs (e.g., issue refunds).",
          rationale: "Keeps dangerous write operations strictly bounded and audited.",
          tradeoffs: ["Requires strict validation loops before execution"],
          illustrative: true,
          pos: { x: 75, y: 70 },
        },
        {
          id: "vector-db",
          label: "Knowledge Store",
          kind: "store",
          tech: ["pgvector", "PostgreSQL"],
          summary: "Stores embedded articles and past resolutions.",
          rationale: "Relational + Vector capabilities in one datastore simplifies ops.",
          tradeoffs: ["Scaling vector indexes requires careful tuning"],
          illustrative: true,
          pos: { x: 25, y: 90 },
        },
      ],
      edges: [
        { id: "e1", from: "ui-client", to: "api-gateway", kind: "sync", label: "GraphQL" },
        { id: "e2", from: "api-gateway", to: "orchestrator", kind: "async", label: "Task stream" },
        { id: "e3", from: "orchestrator", to: "retrieval-agent", kind: "sync", label: "Delegate query" },
        { id: "e4", from: "orchestrator", to: "action-agent", kind: "sync", label: "Delegate action" },
        { id: "e5", from: "retrieval-agent", to: "vector-db", kind: "sync", label: "Search" },
      ],
    },
  ],
  flows: [
    {
      id: "ticket-resolution",
      title: "Agentic Ticket Resolution",
      layerId: "container",
      summary: "How an incoming request is triaged, researched, and acted upon.",
      steps: [
        { nodeId: "ui-client", caption: "CSR submits a natural language request to resolve a ticket." },
        { nodeId: "orchestrator", caption: "The orchestrator analyzes intent and drafts an execution plan." },
        { nodeId: "retrieval-agent", caption: "Orchestrator delegates to the retrieval agent to find relevant policies." },
        { edgeId: "e5", caption: "Vector search over historical resolutions and company handbooks." },
        { nodeId: "action-agent", caption: "With context loaded, orchestrator delegates to the action agent to apply the refund." },
      ],
    },
  ],
};
