export const siteConfig = {
  name: "Rohan P. Suresh",
  title: "Rohan P. Suresh — Full Stack Developer",
  description:
    "I help startups and businesses turn ideas into reliable, scalable software — from first prototype to production. Full Stack Developer specializing in React, React Native, Next.js, Node.js & AI integration.",
  tagline: "I build products that scale.",
  url: process.env.NEXT_PUBLIC_SITE_URL || "https://rohansuresh.dev",
  contact: {
    email: "rohan@codenforge.com",
    phone: "+91 8921355003",
    location: "Kottayam, Kerala, India",
    whatsapp: "https://wa.me/918921355003",
  },
  social: {
    github: "https://github.com/rohanps630",
    linkedin: "https://linkedin.com/in/rohanpsuresh",
  },
  stats: [
    { label: "Years Experience", value: "4.5+" },
    { label: "Products Shipped", value: "6+" },
    { label: "Teams Led", value: "5+" },
  ],
  nav: [
    { label: "Home", href: "/" },
    { label: "About", href: "/about" },
    { label: "Projects", href: "/projects" },
    { label: "Services", href: "/services" },
    { label: "Blog", href: "/blog" },
    { label: "Contact", href: "/contact" },
  ],
  techStack: [
    "React",
    "React Native",
    "Next.js",
    "TypeScript",
    "Node.js",
    "NestJS",
    "Python",
    "Django",
    "Kotlin",
    "MongoDB",
    "PostgreSQL",
    "Docker",
    "AWS",
    "Tailwind CSS",
    "GraphQL",
    "WebSockets",
  ],
} as const;
